version: '3.8'
services:
  mysql:
    container_name: flashpipi-blog-mysql:1.0
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - /mysql/conf:/etc/mysql/conf.d
      - /mysql/logs:/logs
      - /mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'blog_flash_pipi'
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: flashpipi-blog-redis:1.0
    image: redis:7.4.0
    ports:
      - "6379:6379"
    volumes:
      - /redis/data:/data
    command: "redis-server"

  web:
    container_name: flashpipi-blog-web:1.0
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - 8080:8080
    volumes:
      - /conf/flashpipi-blog:/conf/flashpipi-blog
    command:
      - "java"
      - "-jar"
      - "flashpipi-server.jar"
      - "--spring.config.location=/conf/flashpipi-blog/application.yml"
    depends_on:
      - mysql
      - redis

  frontend:
    container_name: flashpipi-blog-frontend:1.0
    build:
      context: .
      dockerfile: Dockerfile-vue
    ports:
      - 80:80
    volumes:
      - /resource/flashpipi-blog/frontend:/usr/share/nginx/html
    depends_on:
      - web


