version: '3.8'
services:
  mysql:
    container_name: flashpipi-blog-mysql
    image: mysql:8.0
    volumes:
      - /project/flashpipi-blog/mysql/conf:/etc/mysql/conf.d
      - /project/flashpipi-blog/mysql/logs:/logs
      - /project/flashpipi-blog/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'blog_flash_pipi'
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: flashpipi-blog-redis
    image: redis:7.4.0
    volumes:
      - /project/flashpipi-blog/redis/data:/data
    command: "redis-server"

  web:
    container_name: flashpipi-blog-web
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - /project/flashpipi-blog/web/conf:/app/conf
      - /project/flashpipi-blog/web/jar:/app/jar
    command:
      - "java"
      - "-Dfile.encoding=UTF-8"
      - "-jar"
      - "jar/flashpipi-server.jar"
      - "--spring.config.location=conf/application.yml"
    depends_on:
      - mysql
      - redis

  frontend:
    container_name: flashpipi-blog-frontend
    build:
      context: .
      dockerfile: Dockerfile-vue
    ports:
      - "80:80"
    volumes:
      - /project/flashpipi-blog/resource/frontend:/usr/share/nginx/html
      - /project/flashpipi-blog/nginx/conf:/etc/nginx
    depends_on:
      - web


