services:
  mysql1:
    container_name: flashpipi-blog-mysql1
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog_flash_pipi
    ports:
      - "23306:3306"
    command: >
      --server-id=1
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
      --log_bin=binlog
      --binlog_format=ROW
      --master_info_repository=TABLE
      --relay_log_info_repository=TABLE
      --transaction_write_set_extraction=XXHASH64
      --loose-group_replication_group_name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      --loose-group_replication_start_on_boot=OFF
      --loose-group_replication_local_address=mysql1:33061
      --loose-group_replication_group_seeds="mysql1:33061,mysql2:33062,mysql3:33063"
      --default_authentication_plugin=mysql_native_password
    volumes:
      - ./data/mysql1:/var/lib/mysql

  mysql2:
    container_name: flashpipi-blog-mysql2
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog_flash_pipi
    ports:
      - "23307:3306"
    command: >
      --server-id=2
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
      --log_bin=binlog
      --binlog_format=ROW
      --master_info_repository=TABLE
      --relay_log_info_repository=TABLE
      --transaction_write_set_extraction=XXHASH64
      --loose-group_replication_group_name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      --loose-group_replication_start_on_boot=OFF
      --loose-group_replication_local_address=mysql2:33062
      --loose-group_replication_group_seeds="mysql1:33061,mysql2:33062,mysql3:33063"
      --default_authentication_plugin=mysql_native_password
    volumes:
      - ./data/mysql2:/var/lib/mysql

  mysql3:
    container_name: flashpipi-blog-mysql3
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog_flash_pipi
    ports:
      - "23308:3306"
    command: >
      --server-id=3
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
      --log_bin=binlog
      --binlog_format=ROW
      --master_info_repository=TABLE
      --relay_log_info_repository=TABLE
      --transaction_write_set_extraction=XXHASH64
      --loose-group_replication_group_name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      --loose-group_replication_start_on_boot=OFF
      --loose-group_replication_local_address=mysql3:33063
      --loose-group_replication_group_seeds="mysql1:33061,mysql2:33062,mysql3:33063"
      --default_authentication_plugin=mysql_native_password
    volumes:
      - ./data/mysql3:/var/lib/mysql

  mysql-router:
    container_name: flashpipi-mysql-router
    image: mysql/mysql-router:8.0
    restart: always
    depends_on:
      - mysql1
      - mysql2
      - mysql3
    ports:
      - "6446:6446" # 读写路由
      - "6447:6447" # 只读路由
    environment:
      MYSQL_HOST: mysql1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_INNODB_CLUSTER_MEMBERS: mysql1:3306,mysql2:3306,mysql3:3306
      MYSQL_CREATE_ROUTER_USER: "true"
      MYSQL_ROUTER_BOOTSTRAP_EXTRA_OPTIONS: "--force"
    volumes:
      - ./data/mysqlrouter:/work/mysqlrouter

  redis:
    container_name: flashpipi-blog-redis
    image: redis:7.4.0
    volumes:
      - ./data/redis/data:/data
    command: "redis-server"
    ports:
      - "26379:6379"

#  elasticsearch:
#    container_name: flashpipi-blog-elasticsearch
#    image: elasticsearch:8.18.4
#    volumes:
#      - ./data/elasticsearch:/usr/share/elasticsearch/data
#    ports:
#      - "29200:9200"
#      - "29300:9300"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    environment:
#      - discovery.type=single-node
#      - ES_JAVA_OPTS=-Xms1g -Xmx1g
#      - bootstrap.memory_lock=true
#      - ELASTIC_PASSWORD=A123456
#      - xpack.security.enabled=true